In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

input\glaucoma.csv
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\001.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\002.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\003.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\004.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\005.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\006.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\007.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\008.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\009.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\010.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\011.jpg
input\Fundus_Train_Val_Data\Fundus_Scanes_Sorted\Train\Glaucoma_Negative\012.jpg
input\Fun

In [2]:
data = pd.read_csv('input/glaucoma.csv')

y_train = data['Glaucoma']
data.head()

Filename  ExpCDR Eye Set  Glaucoma
0  001.jpg  0.7097  OD   A         0
1  002.jpg  0.6953  OS   A         0
2  003.jpg  0.9629  OS   A         0
3  004.jpg  0.7246  OD   A         0
4  005.jpg  0.6138  OS   A         0

In [3]:
from numpy import asarray

from PIL import Image
# load the image
image = Image.open('input/Fundus_Train_Val_Data/Fundus_Scanes_Sorted/Validation/Glaucoma_Positive/613.jpg')
# summarize some details about the image
print(image.format)
print(image.mode)
print(image.size)
# show the image
image.show()
pixels = asarray(image)

JPEG
RGB
(3072, 2048)


In [4]:
# global centering

# calculate global mean
mean = pixels.mean()
print('Mean: %.3f' % mean)
print('Min: %.3f, Max: %.3f' % (pixels.min(), pixels.max()))
# global centering of pixels
pixels = pixels - mean
# confirm it had the desired effect
mean = pixels.mean()
print('Mean: %.3f' % mean)
print('Min: %.3f, Max: %.3f' % (pixels.min(), pixels.max()))
print(pixels)

Mean: 73.462
Min: 0.000, Max: 255.000
Mean: 0.000
Min: -73.462, Max: 181.538
[[[-71.46201356 -71.46201356 -73.46201356]
  [-71.46201356 -71.46201356 -73.46201356]
  [-71.46201356 -71.46201356 -73.46201356]
  ...
  [-72.46201356 -72.46201356 -73.46201356]
  [-72.46201356 -72.46201356 -73.46201356]
  [-72.46201356 -72.46201356 -73.46201356]]

 [[-71.46201356 -71.46201356 -73.46201356]
  [-71.46201356 -71.46201356 -73.46201356]
  [-71.46201356 -71.46201356 -73.46201356]
  ...
  [-72.46201356 -72.46201356 -73.46201356]
  [-72.46201356 -72.46201356 -73.46201356]
  [-72.46201356 -72.46201356 -73.46201356]]

 [[-71.46201356 -71.46201356 -73.46201356]
  [-71.46201356 -71.46201356 -73.46201356]
  [-71.46201356 -71.46201356 -73.46201356]
  ...
  [-72.46201356 -72.46201356 -73.46201356]
  [-72.46201356 -72.46201356 -73.46201356]
  [-72.46201356 -72.46201356 -73.46201356]]

 ...

 [[-73.46201356 -73.46201356 -73.46201356]
  [-73.46201356 -73.46201356 -73.46201356]
  [-73.46201356 -73.46201356 -73.

In [5]:
# example of pixel normalization
# confirm pixel range is 0-255
print('Data Type: %s' % pixels.dtype)
print('Min: %.3f, Max: %.3f' % (pixels.min(), pixels.max()))
# convert from integers to floats
pixels = pixels.astype('float32')
# normalize to the range 0-1
pixels /= 255.0
mean = pixels.mean()
print('pixel mean = ', mean)

Data Type: float64
Min: -73.462, Max: 181.538
pixel mean =  1.3986008e-09


In [6]:
# confirm the normalization
print('Min: %.3f, Max: %.3f' % (pixels.min(), pixels.max()))
print(pixels)

Min: -0.288, Max: 0.712
[[[-0.2802432  -0.2802432  -0.28808632]
  [-0.2802432  -0.2802432  -0.28808632]
  [-0.2802432  -0.2802432  -0.28808632]
  ...
  [-0.28416476 -0.28416476 -0.28808632]
  [-0.28416476 -0.28416476 -0.28808632]
  [-0.28416476 -0.28416476 -0.28808632]]

 [[-0.2802432  -0.2802432  -0.28808632]
  [-0.2802432  -0.2802432  -0.28808632]
  [-0.2802432  -0.2802432  -0.28808632]
  ...
  [-0.28416476 -0.28416476 -0.28808632]
  [-0.28416476 -0.28416476 -0.28808632]
  [-0.28416476 -0.28416476 -0.28808632]]

 [[-0.2802432  -0.2802432  -0.28808632]
  [-0.2802432  -0.2802432  -0.28808632]
  [-0.2802432  -0.2802432  -0.28808632]
  ...
  [-0.28416476 -0.28416476 -0.28808632]
  [-0.28416476 -0.28416476 -0.28808632]
  [-0.28416476 -0.28416476 -0.28808632]]

 ...

 [[-0.28808632 -0.28808632 -0.28808632]
  [-0.28808632 -0.28808632 -0.28808632]
  [-0.28808632 -0.28808632 -0.28808632]
  ...
  [-0.28416476 -0.28416476 -0.28416476]
  [-0.28416476 -0.28416476 -0.28416476]
  [-0.28416476 -0.28

In [7]:
# visualization
import matplotlib.pyplot as plt
fig, (ax0, ax1) = plt.subplots(1, 2)
ax0.imshow(image)
ax0.axis('off')
ax0.set_title('image')
ax1.imshow(pixels)
ax1.axis('off')
ax1.set_title('result')
plt.show()

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).


<Figure size 640x480 with 2 Axes>